<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // 실행 순서: catch -> catch
      new Promise((resolve, reject) => {
        throw new Error("에러 발생!");
      })
        .catch(function (error) {
          // (*)

          if (error instanceof URIError) {
            // 에러 처리
            alert("URIError 발생");
          } else {
            alert("처리할 수 없는 에러");

            throw error; // 에러 다시 던지기
          }
        })
        .then(function () {
          alert("catch에서 에러를 던진 후의 체이닝 호출 (then)");
          /* 여기는 실행되지 않습니다. */
        })
        .catch((error) => {
          // (**)

          alert(`알 수 없는 에러가 발생함: ${error}`);
          // 반환값이 없음 => 실행이 계속됨
        });
    </script>
  </body>
</html>
